[package]
name = "fopencookie"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["sys"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fopencookie-sys = { version = "0.1.0", path = "sys" }
libc = "0.2.154"
